---
name: Brendan Filkins
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: MBA
position: Data Science Leader
address: Burlington, Vermont
email: brendan.e.filkins@gmail.com
github: bfilkins
linkedin: brendan-filkins
headcolor: "414141"
aboutme: Leader in data science and strategy with 7 years experience generating actionable insights and business value from data through quantitative analysis, modeling, data storytelling and bringing business stakeholders together.
output: 
  vitae::awesomecv:
    keep_tex: False
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Experience
```{r consulting}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Manager: Data Science and Client Strategy", "IXIS Digital", "Burlington, Vermont", "July 2021 - Present", 
  list(
    "Leadership of cross-functional team of Data Scientists, Analysts and UI/UX designer",
    "Optimization for media deployment strategies through marketing spend modeling",
    "Model multi-touch channel attribution, digital personalization and conversion propensity scores",
    "Develop executive level KPI frameworks and dashboards for digital, sales, supplychain and marketing audiences",
    "Interface with clients to identify opportunties to use data to create business value, specializing in applied data science",
    "Package development and code review for scalable data engineering pipelines in AWS",
    "A/B testing design and methodology governance",
    "Support team members in professional development through goal setting and advocating for development opportunities",
    "Consulting project clients include: Audi, Nutrisystem, Proflowers.com"
    ),
  "Data Scientist and Strategist", "", "", "July 2020 - July 2021", 
  list(
    "Digital and marketing analytics/modeling to inform marketing spend strategies and digital customer experience", 
    "Time-series analysis and automated anomaly detection in R adjusted for seasonality and trend",
    "Classification modeling in R for customer propensity modeling",
    "Develop interactive R Shiny apps/dashboards for internal and external use",
    "Survival analysis for customer churn in R to support customer life-time value modeling",
    "Structure data in AWS for Machine Learning pipelines, S3, Athena and Glue"
    ),
  "Senior Financial Analyst", "National Life Group", "Burlington, Vermont", "2016-2020", 
  list(
    "Interface with key business stakeholders to leverage data to support strategic decision-making",
    "Build Interactive dashboard design in Tableau",
    "Complete S\\&P Global Market Intelligence: Certified Insurance Analyst program",
    "ETL and data architecture with Alteryx, SQL and Python",
    "Financial planning and analysis for life insurance operations teams",
    "Customer experience and digital engagement analytics",
    "Predictive analytics to inform customer chrun mitigation strategies",
    "Time-series forecasting of sales for capacity planning models",
    "Integration of optimization, clustering and forecasting models in Tableau with Rserve",
    "Data steward for governance processes related to implementation of an enterprise data model"
    )
  ) %>% 
  detailed_entries(role, dates, company, loc, details)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "Masters in Business Administration", "Champlain College", "Burlington, Vermont", "2017-2019", 
  list(
      "Course work in business leadership, statistics, marketing, change management, financial decision-making"
      ),
    "Graduate Certificate in Supply Chain Management", "", "", "2018", 
  list(
      "Supply chain optmization modeling including linear and mixed-integer programming",
      "Analytics for supply chain decision-making including demand forecasting with ARIMA",
      "Probability and statistics including bayesian methodologies"
      ),
  "BS in Psychology", "University of Vermont", "Burlington, Vermont", "2012", 
  list(
    "Course work in organizational psychology, statistics, mathematics, research methods, economics, marketing, spanish, biopsychology"
      )
  ) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Tools
R, Tableau, AWS (S3, Athena, Glue), Python, Spark, Docker, SQL, Excel, GIT, Alteryx, Jira, HTML, Shiny